# Generated by Django 5.1.2 on 2025-02-22 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuActive', models.BooleanField(default=False, verbose_name='Active?')),
                ('menuService', models.BooleanField(default=False, verbose_name='Table Service?')),
                ('menuDescription', models.CharField(max_length=255, verbose_name='Menu')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'ordering': ['menuDescription'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printName', models.CharField(max_length=255, null=True, unique=True, verbose_name='Printer')),
                ('printType', models.CharField(max_length=25)),
                ('printIdVendor', models.PositiveIntegerField(null=True)),
                ('printIdProduct', models.PositiveIntegerField(null=True)),
                ('printIn_ep', models.PositiveIntegerField(null=True)),
                ('printOut_ep', models.PositiveIntegerField(null=True)),
                ('printMacAddress', models.CharField(max_length=17, null=True)),
            ],
            options={
                'ordering': ['printName'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodDescription', models.CharField(max_length=255, verbose_name='Product')),
                ('prodPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('prodVAT', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='VAT (%)')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'ordering': ['prodclassQuery', 'prodDescription'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('companyAdress1', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('companyAdress2', models.CharField(blank=True, max_length=255, verbose_name='Zip, City')),
                ('companyInfo1', models.CharField(blank=True, max_length=255, verbose_name='Add. Information 1')),
                ('companyInfo2', models.CharField(blank=True, max_length=255, verbose_name='Add. Information 2')),
                ('taxIdNumber', models.CharField(blank=True, max_length=255, verbose_name='Tax Number')),
                ('emailHost', models.CharField(blank=True, max_length=255, verbose_name='Email Host')),
                ('emailUser', models.CharField(blank=True, max_length=255, verbose_name='Email User')),
                ('emailPassword', models.CharField(blank=True, max_length=255, verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDtOpen', models.DateTimeField(auto_now_add=True)),
                ('orderDtClose', models.DateTimeField(auto_now=True)),
                ('orderStatus', models.IntegerField(default=0, verbose_name='Order Status')),
                ('orderTable', models.CharField(max_length=25, verbose_name='Table')),
                ('menuQuery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='simorder.menu', verbose_name='Menu')),
                ('orderUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='printQuery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simorder.printer', verbose_name='Receipt Printer'),
        ),
        migrations.AddField(
            model_name='menu',
            name='prodQuery',
            field=models.ManyToManyField(to='simorder.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classDescription', models.CharField(max_length=255, unique=True, verbose_name='Description')),
                ('classColor', models.CharField(default='#0d6efd', max_length=7, verbose_name='Display color')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active?')),
                ('printQuery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simorder.printer', verbose_name='Order Printer')),
            ],
            options={
                'verbose_name': 'Product Class',
                'verbose_name_plural': 'Product Classes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prodclassQuery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='simorder.productclass', verbose_name='Product Class'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poStatus', models.IntegerField(default=0, verbose_name='Product Order Status')),
                ('poTransNumber', models.CharField(blank=True, max_length=20, verbose_name='Transaction Number')),
                ('poPayAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('poPayMethod', models.CharField(blank=True, choices=[('CH', 'Cash'), ('DC', 'Debit card'), ('CC', 'Credit card')], max_length=2)),
                ('poDtOpen', models.DateTimeField(auto_now_add=True)),
                ('poDtClose', models.DateTimeField(auto_now=True)),
                ('poProdDescription', models.CharField(max_length=255)),
                ('poProdPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poProdVAT', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poProdClass', models.CharField(max_length=255)),
                ('poOrder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simorder.order', verbose_name='Order')),
                ('prodQuery', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simorder.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prodQuery',
            field=models.ManyToManyField(through='simorder.ProductOrder', to='simorder.product'),
        ),
    ]
