# Generated by Django 5.1.2 on 2025-02-24 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodStock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
    ]
